### ISSUE TITLE
How to deploy this game - Couldn't Find DB

### ISSUE THREAD

**Issue by A-Shan-stack** [codergautam/battleship#2]
can you please tell us how to set this up ???

**Comment by codergautam** [comment]
Here is DB SQL File:
https://gofile.io/d/HgsxpS

EDIT UPDATED LINK: https://drive.google.com/file/d/165Mt4DZk6oR-VNghvjrJlMaX2tXc616V/view?usp=sharing

**Comment by codergautam** [comment]
Use that for your mySql file and in conn.php make sure to put connection details and that's it. If you have an issue, reply here.

**Comment by A-Shan-stack** [comment]
Thank you so much sir means a lot 😊

**Comment by mustasim988** [comment]
Please send database

**Comment by codergautam** [comment]
https://gofile.io/d/HgsxpS

**Comment by codergautam** [comment]
Sorry, that old link broke.. Here's a new one https://drive.google.com/file/d/165Mt4DZk6oR-VNghvjrJlMaX2tXc616V/view?usp=sharing

**Comment by A-Shan-stack** [comment]
Thanks bro

**Comment by mustasim988** [comment]
> Sorry, that old link broke.. Here's a new one https://drive.google.com/file/d/165Mt4DZk6oR-VNghvjrJlMaX2tXc616V/view?usp=sharing

Thanks Bro

**Comment by codergautam** [comment]
Np
